# This is a basic workflow to help you get started with Actions

name: Deploy to pypi

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        repository:
          type: choice
          description: Do you want to Deploy on TestPyPI or PyPI?
          options: 
          - testpypi
          - pypi
          default: 'testpypi' 
          required: true 
        bump_version:
          type: choice
          description: Which part of version to bump?
          options: 
          - major
          - minor
          - patch
          default: 'patch'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine
    - name: Bump Patch Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version --current-version $(python setup.py --version ) ${{ inputs.bump_version }} setup.py
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '.'
        author_name: mufaddal1125
        author_email: mufaddal1125@gmail.com
        message: bump version
        
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: bump-version
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
      - name: Install deps
        run: python3 -m pip install --upgrade build
      - name: Build package
        run: python3 -m build
      - name: Publish to PyPI
        if: github.event.inputs.repository == 'pypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish package to TestPyPI
        if: github.event.inputs.repository == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "README.md"
